### ISSUE TITLE
(ToDo) A.R. Planet Configuration

### ISSUE THREAD

**Issue by Vaygrim** [GrimCo/CoopLife2#3]
Track "Advanced Rocketry" planets creation / configuration here.

List of Planets with Description, Atmosphere, Name, and Dimension Number (if appropriate)
- Main System
  - Overworld - Breathable - Gallus - Dim 0
  - Overworld Moon - No Atmosphere - Sonneratii - Dim 20
  - Desert World - Breathable - Welsmer - Dim 21
  - Gas Giant - Needs Gasses Added - Australorp

**Comment by mallrat208** [comment]
So for consideration... Advanced Rocketry offers a ton of options when it comes to defining the planets you can visit or at least harvest. 

A very useful link for anyone looking to get involved with this kind of stuff is for the documentation for how everything is defined:
http://65.78.115.159:8000/AdvancedRocketry/config/AdvancedPlanetConfiguration.php

For the TL;DR of it
Within the Galaxy you make you are able to create any number of Star Systems (Single Star only)
You can name the Stars, define their Temperature (color), number of planets, as well as their 'position' as plotted on a map
Each Star can have  any number of Planets
Planets come in two varieties, normal 'worlds' and gas giants, both of which may have any number of Satelites (Moons) which are configured the same way as normal planets
Normal Planetoids are their own dimension (or can be linked to an existing one).
Gas Giants cannot be landed on but you can harvest materials from them with the appropriate probe

When Using AR to define a Planet, you can specify:

- If it's linked to an existing Dimension (like the Overworld or a Dimension added by another mod)
- It's Dimension ID so that you can have predefined dimension numbers allowing for easier ore defining using say COFHWorld
- If the Planet is known(If you can reach it without further research)
- Fog Color
- Sky Color
- Atmosphere Density (if the air is breathable)
- Gravity
- OreGen
- Length of day
- Filler Block (You can have a Nether World that's actually got netherrack)
- Ocean Fluid (Seas of Cryotheum anyone?)
- Sea Level
- Biomes
- Planetary Icon,
- Artifact 'KEY' required to access the planet.

It's also worth mentioning that on top of planets, you can also define Asteroids that can be harvested by rocket mining missions. This probably warrants it's own section as it can also be pretty involved

**Comment by mallrat208** [comment]
As a running gag, since this is Coop Life 2 after all, I'd suggest we name any star systems after Breeds of Chickens.

**Comment by FoxBotGames** [comment]
The question is do we want people launching probes and doing research or do we want all the planets unlocked? Or how about just the starting System and you have to research to leave the system?

**Comment by FoxBotGames** [comment]
MR added in a small system for the starting system, added in a gas giant and a desert.
0.6 will include this

**Comment by FoxBotGames** [comment]
AR no longer in pack, moved to GC
planets added have been removed due to incompatibility with GC
