### ISSUE TITLE
0.8.5 plate integration between mods

### ISSUE THREAD

**Issue by popps73x** [GrimCo/CoopLife2#33]
TE compactor.  Tech Reborn Gold plate and Galacticraft compressed iron seem to be overriding the TE result of the craft.  also the TE plates all seem to have EMC but the ones from tech reborn and galacticraft do not.  not sure if that is intentional or if something needs to be done with an oredict declaration.

**Comment by FoxBotGames** [comment]
So long as the intended result is a gold plate/compressed iron regardless of modID this is not an issue. (We can not change intended item target from what I know, this is multiple items with the same recipe with the same result and one modID is prioritizing over the other's)
Check over and see if these items can still be used in crafting regardless of item modID
To check oreDict use `/ct hand` while the item in question is in hand, recipes will say they use oreDict when mousing over an item.
I can not recommend disabling any item as seen with TGs lead(?) in Wasted as we have no clue if every processing system comes out to the same result. 
I recommend we add EMC to GC and TR plates, mimic EMC values of TE plates.

**Comment by FoxBotGames** [comment]
MR swapped the order they get manipulated, should favor plates over compressed stuff

**Comment by mallrat208** [comment]
It's a bit of a plate lottery right now due to how items get registered to the ore dictionary, however there's not much we can do for it without some serious extensive recipe tweaks. Everything should work now and all plates, ingots, and nuggets, should have their proper ore tag. 

I'm going to go ahead and close this now, if we run into any plate/nugget/ingot that does not work, open up a new issue.
