### ISSUE TITLE
Duplicating items in ProjectE table

### ISSUE THREAD

**Issue by Porthiir** [GrimCo/CoopLife2#46]
Luckily I only lost a few million EMC before noticing the problem.

Certain items once learned show twice in the table, upon "forgetting" that item, one "copy" of the item still remains. If you try clicking that item however, you lose the equivalent EMC but get no item.

**Comment by FoxBotGames** [comment]
This is a known bug with Project E that, for all I know, the Project E devs know about.
Many of the double item in the table are from the very mod and so far we see no fix in the matter (ha matter)
HOWEVER forgetting that item removes BOTH copies of the item not just one. The GUI does not update until you exit and reenter into it. You were probably seeing a ghost item that the table failed to remove and it was spending EMC trying to gain an item that did not exist.
(this being because of the way they have the icons appearing and dis-appearing)

**Comment by FoxBotGames** [comment]
Just confirmed this is an actual issue, ignore my previous comment...
reported to devs (as seen above)

**Comment by FoxBotGames** [comment]
Waiting to update Project E without causing the server to die before we can test to see if this is fixed
(As of 1.0,5 CL2)
